<?php

namespace SynergiTech\TypeScriptGenerator\Services;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Illuminate\Http\Resources\MissingValue;
use ReflectionClass;
use Throwable;

class ResourceGenerator
{
    protected array $config;
    protected Filesystem $files;

    /** @var array<string, string> Resource FQCN → TypeScript interface name */
    protected array $resourceMap = [];

    public function __construct(array $config)
    {
        $this->config = $config;
        $this->files = new Filesystem();
    }

    // -----------------------------------------------------------------------
    //  Public API
    // -----------------------------------------------------------------------

    /**
     * Run the full resource generation pipeline.
     *
     * @return array{generated: string[], skipped: string[], errors: array<string, string>}
     */
    public function generate(): array
    {
        $resources = $this->discoverResources();
        $results = ['generated' => [], 'skipped' => [], 'errors' => []];

        if (empty($resources)) {
            return $results;
        }

        foreach ($resources as $resourceClass) {
            $this->resourceMap[$resourceClass] = class_basename($resourceClass);
        }

        $outputDir = $this->resolvePath($this->config['resource_output_directory'] ?? 'resources/js/types/resources');
        $this->ensureDirectory($outputDir);

        foreach ($resources as $resourceClass) {
            if (in_array($resourceClass, $this->config['excluded_resources'] ?? [], true)) {
                $results['skipped'][] = $resourceClass;
                continue;
            }

            try {
                $definition = $this->generateForResource($resourceClass);
                $filename = class_basename($resourceClass) . '.d.ts';
                $this->files->put($outputDir . '/' . $filename, $definition);
                $results['generated'][] = $resourceClass;
            } catch (Throwable $e) {
                $results['errors'][$resourceClass] = $e->getMessage();
            }
        }

        if (! empty($results['generated'])) {
            $this->generateResourceIndex($outputDir, $results['generated']);
        }

        return $results;
    }

    // -----------------------------------------------------------------------
    //  Resource Discovery
    // -----------------------------------------------------------------------

    /**
     * Scan the configured resource directory and return all JsonResource FQCNs.
     *
     * @return string[]
     */
    public function discoverResources(): array
    {
        $directory = $this->resolvePath($this->config['resource_directory'] ?? 'app/Http/Resources');

        if (! $this->files->isDirectory($directory)) {
            return [];
        }

        $namespace = $this->config['resource_namespace'] ?? 'App\\Http\\Resources';
        $resources = [];

        foreach ($this->files->allFiles($directory) as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }

            $relativePath = $file->getRelativePathname();
            $className = $namespace . '\\' . str_replace(['/', '.php'], ['\\', ''], $relativePath);

            if (! class_exists($className)) {
                continue;
            }

            $reflection = new ReflectionClass($className);

            if (
                $reflection->isAbstract() ||
                $reflection->isInterface() ||
                $reflection->isTrait() ||
                ! $reflection->isSubclassOf(JsonResource::class)
            ) {
                continue;
            }

            $resources[] = $className;
        }

        sort($resources);

        return $resources;
    }

    // -----------------------------------------------------------------------
    //  Per-Resource Generation
    // -----------------------------------------------------------------------

    /**
     * Generate the full .d.ts content for a single resource or resource collection.
     */
    public function generateForResource(string $resourceClass): string
    {
        $interfaceName = class_basename($resourceClass);
        $isCollection = is_subclass_of($resourceClass, ResourceCollection::class);

        $lines = [];
        $lines[] = '// Auto-generated by laravel-typescript-generator';
        $lines[] = '// Resource: ' . $resourceClass;
        $lines[] = '// Generated at: ' . now()->toIso8601String();
        $lines[] = '';

        if ($isCollection) {
            return $this->generateForCollection($resourceClass, $interfaceName, $lines);
        }

        $properties = $this->resolveResourceProperties($resourceClass);

        $imports = $this->collectImports($properties);
        foreach ($imports as $import) {
            $lines[] = "import type { {$import} } from './{$import}';";
        }

        if (! empty($imports)) {
            $lines[] = '';
        }

        $lines[] = "export interface {$interfaceName} {";

        foreach ($properties as $prop) {
            $tsType = $prop['typescript_type'];

            if ($prop['nullable']) {
                $tsType .= ' | null';
            }

            if ($prop['optional']) {
                $lines[] = "  {$prop['name']}?: {$tsType};";
            } else {
                $lines[] = "  {$prop['name']}: {$tsType};";
            }
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate a type alias for a ResourceCollection subclass.
     *
     * @param  string[]  $lines  Header lines already built
     */
    protected function generateForCollection(string $resourceClass, string $interfaceName, array $lines): string
    {
        $collects = $this->findCollectsClass($resourceClass);
        $itemTsType = $collects ? ($this->resourceMap[$collects] ?? class_basename($collects)) : 'unknown';

        if ($collects && isset($this->resourceMap[$collects])) {
            $lines[] = "import type { {$itemTsType} } from './{$itemTsType}';";
            $lines[] = '';
        }

        $lines[] = "export type {$interfaceName} = {$itemTsType}[];";
        $lines[] = '';

        return implode("\n", $lines);
    }

    // -----------------------------------------------------------------------
    //  Property Resolution
    // -----------------------------------------------------------------------

    /**
     * Instantiate the resource with a mock model, call toArray(), and map
     * each returned key/value to a TypeScript property descriptor.
     *
     * @return array<int, array{name: string, typescript_type: string, optional: bool, nullable: bool, import: string|null}>
     */
    protected function resolveResourceProperties(string $resourceClass): array
    {
        $mock = $this->buildMockResource($resourceClass);

        if ($mock === null) {
            return [];
        }

        $array = $mock->toArray(new Request());
        $properties = [];

        foreach ($array as $key => $value) {
            if (! is_string($key)) {
                continue;
            }

            $properties[] = $this->inferProperty($key, $value);
        }

        return $properties;
    }

    /**
     * Map a single key/value pair from toArray() to a property descriptor.
     *
     * @return array{name: string, typescript_type: string, optional: bool, nullable: bool, import: string|null}
     */
    protected function inferProperty(string $key, mixed $value): array
    {
        $base = ['name' => $key, 'optional' => false, 'nullable' => false, 'import' => null];

        if ($value instanceof MissingValue) {
            return array_merge($base, ['typescript_type' => 'unknown', 'optional' => true]);
        }

        // Nested resource collection (e.g. $this->whenLoaded / AnonymousResourceCollection)
        if ($value instanceof AnonymousResourceCollection) {
            $collects = $value->collects ?? null;
            if ($collects && isset($this->resourceMap[$collects])) {
                $itemType = $this->resourceMap[$collects];
                return array_merge($base, ['typescript_type' => "{$itemType}[]", 'import' => $itemType]);
            }
            return array_merge($base, ['typescript_type' => 'unknown[]']);
        }

        // Typed ResourceCollection subclass
        if ($value instanceof ResourceCollection) {
            $collects = $this->findCollectsClass(get_class($value));
            $itemType = $collects ? ($this->resourceMap[$collects] ?? class_basename($collects)) : 'unknown';
            $import = ($collects && isset($this->resourceMap[$collects])) ? $itemType : null;
            return array_merge($base, ['typescript_type' => "{$itemType}[]", 'import' => $import]);
        }

        // Nested single resource
        if ($value instanceof JsonResource) {
            $class = get_class($value);
            $tsType = $this->resourceMap[$class] ?? class_basename($class);
            $import = isset($this->resourceMap[$class]) ? $tsType : null;
            return array_merge($base, ['typescript_type' => $tsType, 'import' => $import]);
        }

        if ($value instanceof \Carbon\Carbon || $value instanceof \Carbon\CarbonImmutable) {
            return array_merge($base, ['typescript_type' => 'string']);
        }

        if (is_null($value)) {
            return array_merge($base, ['typescript_type' => 'unknown', 'nullable' => true]);
        }

        if (is_bool($value)) {
            return array_merge($base, ['typescript_type' => 'boolean']);
        }

        if (is_int($value) || is_float($value)) {
            return array_merge($base, ['typescript_type' => 'number']);
        }

        if (is_string($value)) {
            return array_merge($base, ['typescript_type' => 'string']);
        }

        if (is_array($value)) {
            $type = array_is_list($value) ? 'unknown[]' : 'Record<string, unknown>';
            return array_merge($base, ['typescript_type' => $type]);
        }

        return array_merge($base, ['typescript_type' => 'unknown']);
    }

    // -----------------------------------------------------------------------
    //  Mock Resource Instantiation
    // -----------------------------------------------------------------------

    /**
     * Build a resource instance backed by a mock model or stdClass for introspection.
     */
    protected function buildMockResource(string $resourceClass): ?JsonResource
    {
        $modelClass = $this->findAssociatedModelClass($resourceClass);

        $mock = null;
        if ($modelClass) {
            try {
                $mock = new $modelClass();
            } catch (Throwable) {
                // fall through
            }
        }

        try {
            return new $resourceClass($mock ?? new \stdClass());
        } catch (Throwable) {
            return null;
        }
    }

    /**
     * Attempt to identify the Eloquent model a resource wraps using naming conventions.
     * e.g. UserResource → App\Models\User, UserData → App\Models\User
     */
    protected function findAssociatedModelClass(string $resourceClass): ?string
    {
        $basename = class_basename($resourceClass);
        $modelNamespace = $this->config['model_namespace'] ?? 'App\\Models';

        $candidates = array_unique(array_filter([
            preg_replace('/Resource$/', '', $basename),
            preg_replace('/Data$/', '', $basename),
        ]));

        foreach ($candidates as $candidate) {
            if ($candidate === $basename) {
                continue;
            }
            $fqcn = $modelNamespace . '\\' . $candidate;
            if (class_exists($fqcn) && is_subclass_of($fqcn, Model::class)) {
                return $fqcn;
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    //  Collection Helpers
    // -----------------------------------------------------------------------

    /**
     * Determine what resource class a ResourceCollection subclass collects.
     * Checks the $collects property first, then falls back to naming convention.
     */
    protected function findCollectsClass(string $collectionClass): ?string
    {
        // Check the $collects property (may be set statically on the subclass)
        try {
            $instance = new $collectionClass(collect());
            /** @phpstan-ignore-next-line */
            $collects = $instance->collects ?? null;
            if ($collects && class_exists($collects) && is_subclass_of($collects, JsonResource::class)) {
                return $collects;
            }
        } catch (Throwable) {
            // fall through to convention-based lookup
        }

        // Convention: UsersResource → UserResource (naive singularization)
        $basename = class_basename($collectionClass);
        $namespace = substr($collectionClass, 0, strrpos($collectionClass, '\\') + 1);

        foreach (['Resource', 'Collection'] as $suffix) {
            $stripped = preg_replace('/' . $suffix . '$/', '', $basename);
            if ($stripped === $basename) {
                continue;
            }
            foreach (['Resource', ''] as $append) {
                $candidate = $namespace . rtrim($stripped, 's') . $append;
                if ($candidate !== $collectionClass && class_exists($candidate) && is_subclass_of($candidate, JsonResource::class)) {
                    return $candidate;
                }
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    //  Index / Barrel File
    // -----------------------------------------------------------------------

    /**
     * Generate an index.d.ts that re-exports all generated resource interfaces.
     *
     * @param  string[]  $generatedResources  FQCNs of successfully generated resources
     */
    protected function generateResourceIndex(string $outputDir, array $generatedResources): void
    {
        $lines = ['// Auto-generated barrel file — do not edit manually', ''];

        foreach ($generatedResources as $resourceClass) {
            $name = class_basename($resourceClass);
            $lines[] = "export type { {$name} } from './{$name}';";
        }

        $lines[] = '';

        $this->files->put($outputDir . '/index.d.ts', implode("\n", $lines));
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    /**
     * Collect unique import names from a list of property descriptors.
     *
     * @param  array<int, array{import: string|null}>  $properties
     * @return string[]
     */
    protected function collectImports(array $properties): array
    {
        $imports = [];

        foreach ($properties as $prop) {
            if (isset($prop['import']) && $prop['import'] !== null && ! in_array($prop['import'], $imports, true)) {
                $imports[] = $prop['import'];
            }
        }

        return $imports;
    }

    protected function ensureDirectory(string $path): void
    {
        if (! $this->files->isDirectory($path)) {
            $this->files->makeDirectory($path, 0755, true);
        }
    }

    /**
     * Resolve a config path to an absolute filesystem path.
     * Absolute paths are returned as-is; relative paths are resolved via base_path().
     */
    protected function resolvePath(string $path): string
    {
        return str_starts_with($path, '/') ? $path : base_path($path);
    }
}
