<?php

namespace SynergiTech\TypeScriptGenerator\Services;

use SynergiTech\TypeScriptGenerator\Mappers\TypeMapper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use ReflectionClass;
use ReflectionMethod;
use ReflectionNamedType;
use Throwable;

class TypeScriptGenerator
{
    protected array $config;
    protected Filesystem $files;

    /** @var array<string, string> Model FQCN → TypeScript interface name */
    protected array $modelMap = [];

    public function __construct(array $config)
    {
        $this->config = $config;
        $this->files = new Filesystem();
    }

    // -----------------------------------------------------------------------
    //  Public API
    // -----------------------------------------------------------------------

    /**
     * Run the full generation pipeline.
     *
     * @return array{generated: string[], skipped: string[], errors: array<string, string>}
     */
    public function generate(bool $withRelationships = false): array
    {
        $models = $this->discoverModels();
        $results = ['generated' => [], 'skipped' => [], 'errors' => []];

        // First pass — build a map so relationships can reference sibling types
        foreach ($models as $modelClass) {
            $this->modelMap[$modelClass] = class_basename($modelClass);
        }

        $outputDir = base_path($this->config['output_directory']);
        $this->ensureDirectory($outputDir);

        foreach ($models as $modelClass) {
            if (in_array($modelClass, $this->config['excluded_models'] ?? [], true)) {
                $results['skipped'][] = $modelClass;
                continue;
            }

            try {
                $typeDefinition = $this->generateForModel($modelClass, $withRelationships);
                $filename = class_basename($modelClass) . '.d.ts';
                $this->files->put($outputDir . '/' . $filename, $typeDefinition);
                $results['generated'][] = $modelClass;
            } catch (Throwable $e) {
                $results['errors'][$modelClass] = $e->getMessage();
            }
        }

        // Generate barrel index file that re-exports everything
        $this->generateIndex($outputDir, $results['generated']);

        return $results;
    }

    // -----------------------------------------------------------------------
    //  Model Discovery
    // -----------------------------------------------------------------------

    /**
     * Scan the configured model directory and return all Eloquent model FQCNs.
     *
     * @return string[]
     */
    public function discoverModels(): array
    {
        $directory = base_path($this->config['model_directory']);

        if (! $this->files->isDirectory($directory)) {
            return [];
        }

        $namespace = $this->config['model_namespace'];
        $models = [];

        foreach ($this->files->allFiles($directory) as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }

            // Build the FQCN from the relative path
            $relativePath = $file->getRelativePathname();                // e.g. "User.php" or "Sub/Thing.php"
            $className = $namespace . '\\' . str_replace(
                ['/', '.php'],
                ['\\', ''],
                $relativePath
            );

            if (! class_exists($className)) {
                continue;
            }

            $reflection = new ReflectionClass($className);

            if (
                $reflection->isAbstract() ||
                $reflection->isInterface() ||
                $reflection->isTrait() ||
                ! $reflection->isSubclassOf(Model::class)
            ) {
                continue;
            }

            $models[] = $className;
        }

        sort($models);

        return $models;
    }

    // -----------------------------------------------------------------------
    //  Per-Model Generation
    // -----------------------------------------------------------------------

    /**
     * Generate the full .d.ts content for a single model.
     */
    public function generateForModel(string $modelClass, bool $withRelationships = false): string
    {
        /** @var Model $instance */
        $instance = new $modelClass();

        $interfaceName = class_basename($modelClass);
        $properties = $this->resolveProperties($instance, $modelClass);

        $lines = [];
        $lines[] = '// Auto-generated by laravel-typescript-generator';
        $lines[] = '// Model: ' . $modelClass;
        $lines[] = '// Generated at: ' . now()->toIso8601String();
        $lines[] = '';

        // Collect imports for relationship types
        $imports = [];

        if ($withRelationships) {
            $relationships = $this->resolveRelationships($instance);
            foreach ($relationships as $rel) {
                $relatedType = $rel['typescript_type'];
                // Extract the base type name (strip "[] | null" etc.)
                $baseType = preg_replace('/[\[\]\s|null]+/', '', $relatedType);
                if ($baseType !== 'unknown' && $baseType !== $interfaceName && ! in_array($baseType, $imports, true)) {
                    $imports[] = $baseType;
                }
            }
        }

        // Add import references
        foreach ($imports as $import) {
            $lines[] = "import type { {$import} } from './{$import}';";
        }
        if (count($imports) > 0) {
            $lines[] = '';
        }

        $lines[] = "export interface {$interfaceName} {";

        // --- Attribute properties ---
        foreach ($properties as $prop) {
            $nullable = $prop['nullable'];
            $tsType = $prop['typescript_type'];
            $comment = $prop['comment'] ?? '';

            if ($comment) {
                $lines[] = "  /** {$comment} */";
            }

            if ($nullable && ($this->config['nullable_style'] ?? 'union') === 'optional') {
                $lines[] = "  {$prop['name']}?: {$tsType};";
            } elseif ($nullable) {
                $lines[] = "  {$prop['name']}: {$tsType} | null;";
            } else {
                $lines[] = "  {$prop['name']}: {$tsType};";
            }
        }

        // --- Relationship properties ---
        if ($withRelationships) {
            $relationships = $this->resolveRelationships($instance);
            if (count($relationships) > 0) {
                $lines[] = '';
                $lines[] = '  // Relationships';
                foreach ($relationships as $rel) {
                    $lines[] = "  {$rel['name']}?: {$rel['typescript_type']};";
                }
            }
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    // -----------------------------------------------------------------------
    //  Property Resolution (Schema + Casts + Overrides)
    // -----------------------------------------------------------------------

    /**
     * Merge database schema columns with model casts to produce the final
     * list of typed properties.
     *
     * @return array<int, array{name: string, typescript_type: string, nullable: bool, comment: string}>
     */
    protected function resolveProperties(Model $instance, string $modelClass): array
    {
        $table = $instance->getTable();
        $connection = $instance->getConnectionName();

        $columns = $this->getTableColumns($table, $connection);
        $casts = $instance->getCasts();
        $overrides = $this->config['type_overrides'][$modelClass] ?? [];

        $properties = [];

        foreach ($columns as $column) {
            $name = $column['name'];

            // Skip timestamps if the model has them disabled and config says respect that
            if (
                ! ($this->config['include_timestamps'] ?? false) &&
                ! $instance->usesTimestamps() &&
                in_array($name, [$instance->getCreatedAtColumn(), $instance->getUpdatedAtColumn()], true)
            ) {
                continue;
            }

            // 1) Check manual overrides first
            if (isset($overrides[$name])) {
                $tsType = $overrides[$name];
            }
            // 2) Then check Laravel casts
            elseif (isset($casts[$name])) {
                $tsType = TypeMapper::fromLaravelCast($casts[$name]);
            }
            // 3) Fall back to database column type
            else {
                $tsType = TypeMapper::fromDatabaseType($column['type']);
            }

            $properties[] = [
                'name' => $name,
                'typescript_type' => $tsType,
                'nullable' => $column['nullable'],
                'comment' => $this->buildComment($column, $casts[$name] ?? null),
            ];
        }

        return $properties;
    }

    /**
     * Retrieve column metadata from the database schema.
     *
     * @return array<int, array{name: string, type: string, nullable: bool}>
     */
    protected function getTableColumns(string $table, ?string $connection): array
    {
        $schemaBuilder = Schema::connection($connection);

        // Laravel 11+ has getColumns() which returns rich metadata
        if (method_exists($schemaBuilder, 'getColumns')) {
            return collect($schemaBuilder->getColumns())
                ->map(fn (array $col) => [
                    'name' => $col['name'],
                    'type' => $col['type_name'] ?? $col['type'] ?? 'string',
                    'nullable' => $col['nullable'] ?? true,
                ])
                ->all();
        }

        // Fallback for Laravel 10 — use getColumnListing + getColumnType
        $columnNames = $schemaBuilder->getColumnListing($table);

        return collect($columnNames)
            ->map(fn (string $name) => [
                'name' => $name,
                'type' => $schemaBuilder->getColumnType($table, $name),
                'nullable' => true, // Can't easily determine on L10, default to nullable
            ])
            ->all();
    }

    /**
     * Build a short JSDoc comment describing the source of the type.
     */
    protected function buildComment(array $column, ?string $cast): string
    {
        $parts = [];
        $parts[] = 'DB: ' . $column['type'];

        if ($cast) {
            $parts[] = 'Cast: ' . $cast;
        }

        if ($column['nullable']) {
            $parts[] = 'nullable';
        }

        return implode(' | ', $parts);
    }

    // -----------------------------------------------------------------------
    //  Relationship Resolution
    // -----------------------------------------------------------------------

    /**
     * Detect relationship methods on the model via reflection.
     *
     * @return array<int, array{name: string, type: string, related_model: string, typescript_type: string}>
     */
    protected function resolveRelationships(Model $instance): array
    {
        $reflection = new ReflectionClass($instance);
        $relationships = [];

        foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
            // Skip non-model methods
            if ($method->class !== get_class($instance)) {
                continue;
            }

            // Must have zero required parameters
            if ($method->getNumberOfRequiredParameters() > 0) {
                continue;
            }

            // Check if the return type is a known relationship class
            $returnType = $method->getReturnType();

            if (! $returnType instanceof ReflectionNamedType) {
                continue;
            }

            $returnTypeName = $returnType->getName();

            if (! is_subclass_of($returnTypeName, Relation::class) && $returnTypeName !== Relation::class) {
                continue;
            }

            // Try calling the method to get the related model
            try {
                /** @var Relation $relation */
                $relation = $instance->{$method->getName()}();
                $relatedClass = get_class($relation->getRelated());
                $relationType = class_basename($relation);
                $relatedTsType = $this->modelMap[$relatedClass] ?? class_basename($relatedClass);

                $relationships[] = [
                    'name' => $method->getName(),
                    'type' => $relationType,
                    'related_model' => $relatedClass,
                    'typescript_type' => TypeMapper::fromRelationship($relationType, $relatedTsType),
                ];
            } catch (Throwable) {
                // If we can't resolve it, skip gracefully
                continue;
            }
        }

        return $relationships;
    }

    // -----------------------------------------------------------------------
    //  Index / Barrel File
    // -----------------------------------------------------------------------

    /**
     * Generate an index.d.ts that re-exports all generated interfaces.
     *
     * @param  string[]  $generatedModels  FQCNs of successfully generated models
     */
    protected function generateIndex(string $outputDir, array $generatedModels): void
    {
        $lines = ['// Auto-generated barrel file — do not edit manually', ''];

        foreach ($generatedModels as $modelClass) {
            $name = class_basename($modelClass);
            $lines[] = "export type { {$name} } from './{$name}';";
        }

        $lines[] = '';

        $this->files->put($outputDir . '/index.d.ts', implode("\n", $lines));
    }

    // -----------------------------------------------------------------------
    //  Helpers
    // -----------------------------------------------------------------------

    protected function ensureDirectory(string $path): void
    {
        if (! $this->files->isDirectory($path)) {
            $this->files->makeDirectory($path, 0755, true);
        }
    }
}
